### ISSUE TITLE
Implemented cleantalk for registration but not working

### ISSUE THREAD

**Issue by marshmeloo** [CleanTalk/yii2-antispam#1]
added below in user model
['email', UserValidator::className(), 'nickNameAttribute'=>'username']

added below in registration view 
<?= \cleantalk\antispam\Widget::widget()?>

register with email "ibaaggeva@dfoofmail.com" as it is listed spam on cleantalk but get registered in my application.

show entry on cleantalk server as spam but in my application still get registered
Please help !!
![cleantalk](https://cloud.githubusercontent.com/assets/9282082/11028472/d5174b8e-86e4-11e5-98dc-f03497ef9ea5.PNG)

**Comment by CleanTalk** [comment]
Hello,

the ibaaggeva@dfoofmail.com is not blacklisted at the moment,

https://cleantalk.org/blacklists?record=ibaaggeva%40dfoofmail.com

The service filters only Emails/IPs with status 'Blacklisted'. To test the API please use email stop_email@example.com or any from TOP20 list,

https://cleantalk.org/blacklists/top20

Does it work? Thank you!

**Comment by marshmeloo** [comment]
Hi, 

I tried stop_email@example.com, goodbyeyi1@outlook.com and goodbyeyi2@outlook.com but no luck.

Am'I missing something ??

**Comment by CleanTalk** [comment]
Do you see requests with these emails in your Anti-spam log?

https://cleantalk.org/my/show_requests?int=week

If not please check the 'apiKey' option. It should has same value at yours Dashbboard,

https://cleantalk.org/my/

If the value same please let us know your account id (email) at cleantalk.org. Please send account id privately via welcome at cleantalk dot org. Or submit support request here,

https://cleantalk.org/my/support

Thank you!

**Comment by marshmeloo** [comment]
Yes, I see the emails in Anti-spam log.

![cleantalk1](https://cloud.githubusercontent.com/assets/9282082/11030884/da20bd6a-86f6-11e5-8496-1dd2266bc442.PNG)

**Comment by psrustik** [comment]
Please, show code of registration Controller

**Comment by CleanTalk** [comment]
Thank you for reply!

It was issue with your account. Actually, you have to purchase 1 year license to get API working. In this case you have 60 days for full refund.

But I just applied 2 weeks free trial to your account,

https://cleantalk.org/my/

Please let 10-15 minutes to update your account status on all servers. Then feel free use and test it.

Thank you!

**Comment by marshmeloo** [comment]
Thanks, I will test it and if all my requirement meet will buy it definitely.

**Comment by CleanTalk** [comment]
You are welcome!

Thank you for contacting us.

**Comment by marshmeloo** [comment]
Hi,

Now, I'm getting different issue.

It is blocking stop_email@example.com but also real email id like "anshurcf@gmail.com" with response (Forbidden. Please enable JavaScript.).
And one more think, I'm getting spam from "inmiaji@asdooeemail.com" but i'm getting same response ("Forbidden. Please enable JavaScript.") as real emai id "asnhurcf@gmail.com".

can you please help !!!

![cleantalk2](https://cloud.githubusercontent.com/assets/9282082/11033345/48361a6e-8708-11e5-960e-813081d76dc8.PNG)

**Comment by psrustik** [comment]
Are you added code below to html-form?

``` php
<?= \cleantalk\antispam\Widget::widget()?>
```

You can check that  _ct_checkjs_ hidden input exists in html source.

**Comment by marshmeloo** [comment]
Yes, it is added.

<input type="hidden" id="e3796ae838835da0b6f6ea37bcf8bcb7" name="ct_checkjs" value="-1">
<input type="hidden" name="ct_formid" value="e3796ae838835da0b6f6ea37bcf8bcb7">

**Comment by marshmeloo** [comment]
<pre> input type="hidden" id="e3796ae838835da0b6f6ea37bcf8bcb7" name="ct_checkjs" value="-1" 
 input type="hidden" name="ct_formid" value="e3796ae838835da0b6f6ea37bcf8bcb7"  </pre>

**Comment by psrustik** [comment]
1. May be javascript really is disabled in browser settings? 
2. Please provide logs of registration bug how  it writen in this article 
   https://github.com/CleanTalk/yii2-antispam/wiki/Debugging

**Comment by marshmeloo** [comment]
javascript is enabled in my browser.

below are the logs of registration:

![cleantalk3](https://cloud.githubusercontent.com/assets/9282082/11041260/c5891394-8736-11e5-8409-208665d0a3fe.PNG)

![cleantalk4](https://cloud.githubusercontent.com/assets/9282082/11041229/8d7938e4-8736-11e5-9dbc-6c65718d9c30.PNG)

**Comment by marshmeloo** [comment]
Quick question, Do I need to do something in registration controller (Using dektrium extensiion)?? As in documentation their is no such thing mentioned.

**Comment by psrustik** [comment]
JavaScript test do not pass for your case. Cleantalk request contains js_on=0.

Are you see a code in html-sources how below?

```
<script type="text/javascript">jQuery(document).ready(function () {
setTimeout(function(){document.getElementById("821fa74b50ba3f7cba1e6c53e8fa6845").value="325734aee0b12b377003daa1a2a2650f";}, 1000)
</script>
```

**Comment by marshmeloo** [comment]
No, I don't see this code. So what is wrong ?

**Comment by psrustik** [comment]
Yes, that is wrong. 
 \cleantalk\antispam\Widget has to [register](https://github.com/CleanTalk/yii2-antispam/blob/master/Widget.php#L31) a JS code block for JavaScript test

**Comment by marshmeloo** [comment]
So, how do i fix this ?

**Comment by psrustik** [comment]
Please, send me email with a sample code (model,controller, view,app config, composer.json) where this problem repeats. Perhaps this is due to third-party extension.

psrustik  @ gmail.com

**Comment by marshmeloo** [comment]
Did you received my email ?

**Comment by CleanTalk** [comment]
Hello,

We are sorry for delay. Please let us 1-2 days to figure out the issue.

Thank you!

**Comment by psrustik** [comment]
Issue solved, problem was in 
- Yii2 application layout did not call Asset bundles with code below

``` php
...
<?php $this->endBody() ?>
```
- For  dektrium/user extension cleantalk\antispam\validators\UserValidator rule must add into dektrium\user\models\RegistrationForm model, not User.

**Comment by marshmeloo** [comment]
thanks @psrustik
